### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by worknovel**
Changed self to this, making it work.

### CODE REVIEW

**Comment by Mastermindzh** [comment]
This is not sustainable. The build file is overwritten any time a build occurs.

**Comment by worknovel** [comment]
> 

Would this be the solution for now?
https://github.com/Mastermindzh/react-cookie-consent/issues/136#issuecomment-990733653

**Comment by Mastermindzh** [comment]
@worknovel Kinda. But I just added a "proper" (according to gatsby docs) work-around for gatsby based apps 😄 
See: https://github.com/Mastermindzh/react-cookie-consent/issues/136#issuecomment-990758724

**Comment by worknovel** [comment]
> @worknovel Kinda. But I just added a "proper" (according to gatsby docs) work-around for gatsby based apps 😄
> See: [#136 (comment)](https://github.com/Mastermindzh/react-cookie-consent/issues/136#issuecomment-990758724)

Thank you! Should’ve mentioned that I was referring to a Next JS problem, but I appreciate both answers!

**Comment by Mastermindzh** [comment]
Problem fixed in [7.0.1](https://www.npmjs.com/package/react-cookie-consent/v/7.0.1).

Enjoy!

**Pull request closed without merging**
