### PR TITLE
Auto hide

### PR DESCRIPTION
**Pull request by dimitrisfasoulas**

### CODE REVIEW

**Comment by Mastermindzh** [comment]
we should call this "hideOnAccept" instead, that will more accurately convey it's function :)

**Comment by Mastermindzh** [comment]
Thanks for renaming it @dimitrisfasoulas , I will check and merge later today.

Just did a quick check and all seems well though.

I'll report back when I have a new version on npm!

**Comment by dimitrisfasoulas** [comment]
Thanks for the fast replies 👍

**Comment by Mastermindzh** [comment]
Added in [1.5](https://www.npmjs.com/package/react-cookie-consent/v/1.5.0)

**Comment by Mastermindzh** [comment]
No problem on the fast replies!

For future reference, you don't actually have to edit the build folder next time, it is automatically built using `npm run build`, just edit the src directory and I'll run a build and bump the version :)

I mean it's fine that you edit it, but your edits are deleted with the build command :)

Thanks for the contribution and have a nice week!

**Pull request merged**
