### PR TITLE
✨ Add prop ButtonComponent

### PR DESCRIPTION
**Pull request by charlyx**
Hi 👋

First of all, thanks for your work! 👏

We're beginning to use your component in our project and we're facing an issue.
We've got an homemade library for all our graphic components and we'd like to be able to use our `Button` component.
We'd like to avoid duplicating our component's style to pass it to `buttonStyle` or `buttonClasses`.

I hope you'll agree with my small contribution to your project.

Happy to discuss! 😄

### CODE REVIEW

**Comment by Mastermindzh** [comment]
Hey Charly, 

I'll have a look tomorrow, I got out of hospital last night and I don't think I'll be able to get to it today.

Once I test backwards compatibility and that all checks out this looks like a sensible addition.

Thanks in advance!

**Comment by charlyx** [comment]
@Mastermindzh I hope everything is OK! Thanks for your reply 🙏

I've me done some test myself and fixed my code. I should have added some test to ensure I did not break anything but I could not find any. Maybe in a future PR? If you like.

Take care!

**Comment by Mastermindzh** [comment]
Hey @charlyx ,

Thanks for your contribution.
I like the idea we can change the button for a different react component when we want to and I'm sure to merge that!

I do not really like the capital on the buttonComponent (especially with React 16's move towards all camelCase)

Tell you what, I'll merge the pull-request in and before I release a new version I'll change back to camelCase.

Thanks for editing the description as well btw!

Cheers!

**Comment by charlyx** [comment]
@Mastermindzh thanks!

I didn't have the choice to capitalize `buttonComponent` though... React only allows HTML elements to not be capitalized. Can't we really have a release? ☹️

**Comment by Mastermindzh** [comment]
What do you mean with "react only allows HTML elements to not be capitalized?"

You could still have your react component be capitalized, it would just be the prop that isn't capitalized like so:

```
<CookieConsent buttonComponent={CapitalizedReactComponent}> ...
```

Or did I misunderstand? If I'm doing anything not according to the React rules we surely will have a re-release!

**Comment by charlyx** [comment]
If you look at the render you'll see `<buttonComponent></buttonComponent>` which is wrong as it is not an HTML element.

**Comment by Mastermindzh** [comment]
Hey Charlyx,

Do you have an example of the error?
I have a hard time recreating the error.

**Comment by charlyx** [comment]
Sure, here they are:

```
Warning: <buttonComponent /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
....
Warning: The tag <buttonComponent> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter
```

**Comment by Mastermindzh** [comment]
yeah I just got those, I will revert the commit, thanks for your watchful eye!

**Comment by charlyx** [comment]
You're very welcome!

Please tell me once you've released the new version so I can update the dependency in our project 😄

**Comment by Mastermindzh** [comment]
[Version 2.2.1](https://www.npmjs.com/package/react-cookie-consent/v/2.2.1) should have all you need my friend.

Sorry it took so long, my ISP has stuck me with 200+ pings again today.

**Comment by charlyx** [comment]
Great! 🎉Thank you 😄

**Pull request merged**
