### PR TITLE
Improve debugging

### PR DESCRIPTION
**Pull request by karland**
I did not like to remove the cookie manually, so I added a `debug`-property.

### CODE REVIEW

**Comment by Mastermindzh** [comment]
Any reason to explicitly *delete* the cookie?

We could simply not disable the bar whilst debug is true.

```
 if ((debug !== undefined || !debug) Cookies.get(cookieName) !== undefined) {
      this.setState({ visible: false }); 
 }
```

Only thing that comes to mind is a disappear animation really. Other than that this looks to be pretty smart! I'll merge later today!

**Comment by karland** [comment]
I agree with you, there is no reason to actually delete the cookie.  

However, I am not sure about your if-statement;

```js
(debug === undefined || !debug)
```

If debug is undefined you are checking for !debug. It would rather suggest

```js
!(debug !== undefined && debug)
```

By the way I noticed a version mismatch to npm?

**Comment by karland** [comment]
I just added your and my suggestions to the PR to make your life easier. 

Also I made some more changes for the styling. The bar was not really behaving in a responsive manner on small screens. Media queries would have been the typical solution for this, but do not work in this context. But flexbox comes to the rescue. I chose the minimum-content width to be 300px, which is nice for iPhone 5 and the likes. If the button does not fit into the same line it is wrapped. If it fits and there is still some room, the content is allowed to grow. Pretty neat. For this reason I had to also exchange some paddings for margins.

**Comment by karland** [comment]
I forgot: disappear animation would be nice, indeed.

**Comment by Mastermindzh** [comment]
```
 if ((debug == undefined || !debug) && Cookies.get(cookieName) !== undefined) {
      this.setState({ visible: false }); 
 }
```

if debug is undefined it will resolve to true and it **won't** check the or (`|| !debug` ), instead it will check whether the cookie is set and if so set visibility to false.

if debug is true it will not be undefined and check the or, !debug (which is false) so it won't even check whether there is a cookie and skip the if all together.

if debug is false it will NOT be undefined so it will check !debug (true) and therefore continue on.

That was the logic behind my if statement, it requires the person who reads it to understand what happens with the && and || quite well.

That's where your thinking might have been off, the second part of an OR statement isn't tested if the first evaluates to true :)


As for the code, I will check it tonight and if it looks good I'll merge. I agree that a "debug" feature might be useful whilst testing.

**Comment by karland** [comment]
>if debug is undefined it will resolve to true and it won't check the or (|| !debug ), instead it will check whether the cookie is set and if so set visibility to false.

Agreed. You are right. I was probably confused because is see this scheme quite often:

```js
variable !== defined && variable
```

> That was the logic behind my if statement, it requires the person who reads it to understand what happens with the && and || quite well.

Absolutely agree.

Therefore, I find the following logic easiear to understand and added a corresponding comment:
If debug not desired and cookieName not undefined then visibility false. 

Thanks.

**Comment by Mastermindzh** [comment]
It will be even simpler with a default prop :D

Thanks for your contribution, I'll merge, change to default prop, update package version and push to npm now!

Thanks for your support!

**Comment by Mastermindzh** [comment]
I updated all of it, looks great! Thanks for your contribution!

**Comment by karland** [comment]
Thanks for your fast merge. Making `debug` a default prop is much more straight forward. Shame that I did not think of this myself.

**Pull request merged**
