### PR TITLE
Add TypeScript Definition

### PR DESCRIPTION
**Pull request by Saturate**
Add a TypeScript Definition, and "build" it with webpack to the build folder.

This will add correct typings, if you use TypeScript with React.

#27

### CODE REVIEW

**Comment by Mastermindzh** [comment]
Hey man, thanks for taking the time to develop this.

I got a few things I'd like to change before we merge though.

Consent is written with an "s", you wrote concent instead, so I'd like to change it to use the S instead.
The Javascript file uses 2 spaces for indentation, we should keep that the same for TS I reckon (though I doubt we need a tslint config).
Please remove the I prefix on the interface (as per the typescript handbook)
Again, much-appreciated man! This is some solid work 👍
Fix these few small things and I'll be sure to merge it in ASAP.

**Comment by Saturate** [comment]
Oh, went a little too quick there it seems.
Thanks for pointing it out :-) will fix it soon.

**Comment by Saturate** [comment]
Should now be fixed, out of curiosity can you point me to the point where they say no prefix for interfaces? I think `tslint` wants this by default.

**Comment by Mastermindzh** [comment]
Hey @Saturate, 

The changes look good!

It seems they [changed the handbook](https://github.com/Microsoft/TypeScript-Handbook/issues/121) a while ago, I wasn't aware of that change.
You can apparently use both now. [The React Typescript starter by Microsoft ](https://github.com/Microsoft/TypeScript-React-Starter)(those who wrote the handbook) by default doesn't care whether you prefix or not.

Google is still full of discussions about this specific point, some interesting points of view on there too :)

So... that change wasn't necessary after all :)
I'll merge it like this, thanks for the hard work mate!

I'll push an update immediatelly after the merge too (it will be a minor one)

**Comment by Saturate** [comment]
Hey @Mastermindzh 

Thanks for the update and if you ever visit Copenhagen, I'll (well the company) give you a beer ;)

**Comment by Mastermindzh** [comment]
If you ever visit the Netherlands I'll return that favor man!

Great working with ya!

**Pull request merged**
